import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

const NFT_BASE_URI = "https://motshelo.xyz/api/nft/";

async function main() {
  const signers = await ethers.getSigners();
  const [deployer, alice, bob, charlie] = signers;

  console.log("=== Motshelo Local Dev Deploy ===\n");
  console.log("Deployer:", deployer.address);

  // ─── Deploy Mock Tokens ───
  console.log("\n[1/10] Deploying MockUSDT...");
  const MockUSDT = await ethers.getContractFactory("MockUSDT");
  const usdt = await MockUSDT.deploy();
  await usdt.waitForDeployment();
  const usdtAddr = await usdt.getAddress();
  console.log("        MockUSDT:", usdtAddr);

  console.log("[2/10] Deploying MockAToken...");
  const MockAToken = await ethers.getContractFactory("MockAToken");
  const aToken = await MockAToken.deploy();
  await aToken.waitForDeployment();
  const aTokenAddr = await aToken.getAddress();
  console.log("        MockAToken:", aTokenAddr);

  console.log("[3/10] Deploying MockAavePool...");
  const MockAavePool = await ethers.getContractFactory("MockAavePool");
  const aavePool = await MockAavePool.deploy(usdtAddr, aTokenAddr);
  await aavePool.waitForDeployment();
  const aavePoolAddr = await aavePool.getAddress();
  await aToken.setPool(aavePoolAddr);
  console.log("        MockAavePool:", aavePoolAddr);

  // ─── Deploy Protocol ───
  console.log("[4/10] Deploying FeeCollector...");
  const FeeCollector = await ethers.getContractFactory("FeeCollector");
  const feeCollector = await FeeCollector.deploy(deployer.address);
  await feeCollector.waitForDeployment();
  const fcAddr = await feeCollector.getAddress();
  console.log("        FeeCollector:", fcAddr);

  console.log("[5/10] Deploying MotsheloFactory...");
  const Factory = await ethers.getContractFactory("MotsheloFactory");
  const factory = await Factory.deploy(
    fcAddr,
    ethers.ZeroAddress,
    ethers.ZeroAddress,
    deployer.address,
    ethers.keccak256(ethers.toUtf8Bytes("local-vrf-key")),
    0,
    aavePoolAddr,
    aTokenAddr
  );
  await factory.waitForDeployment();
  const factoryAddr = await factory.getAddress();
  console.log("        Factory:", factoryAddr);

  console.log("[6/10] Wiring FeeCollector -> Factory...");
  await (await feeCollector.updateFactory(factoryAddr)).wait();

  console.log("[7/10] Deploying MotsheloRegistry...");
  const Registry = await ethers.getContractFactory("MotsheloRegistry");
  const registry = await Registry.deploy(factoryAddr);
  await registry.waitForDeployment();
  const regAddr = await registry.getAddress();
  console.log("        Registry:", regAddr);

  console.log("[8/10] Deploying MotsheloNFT...");
  const NFT = await ethers.getContractFactory("MotsheloNFT");
  const nft = await NFT.deploy(NFT_BASE_URI, factoryAddr);
  await nft.waitForDeployment();
  const nftAddr = await nft.getAddress();
  console.log("        NFT:", nftAddr);

  console.log("[9/10] Wiring Factory dependencies + approving USDT...");
  await (await factory.updateDependencies(fcAddr, nftAddr, regAddr)).wait();
  await (await factory.setApprovedToken(usdtAddr, true)).wait();

  // ─── Fund Test Wallets ───
  console.log("[10/10] Minting 100,000 USDT to test accounts...");
  const mintAmount = ethers.parseEther("100000");
  for (let i = 0; i < Math.min(signers.length, 5); i++) {
    await usdt.mint(signers[i].address, mintAmount);
    console.log(`         ${signers[i].address} → 100,000 USDT`);
  }

  // ─── Write addresses to frontend ───
  const addressesContent = `// AUTO-GENERATED by deploy-local.ts — do not edit manually
export const BSC_CHAIN_ID = 56;
export const BSC_TESTNET_CHAIN_ID = 97;
export const HARDHAT_CHAIN_ID = 31337;

export type ContractAddresses = {
  factory: \`0x\${string}\`;
  feeCollector: \`0x\${string}\`;
  registry: \`0x\${string}\`;
  nft: \`0x\${string}\`;
  usdt: \`0x\${string}\`;
  aUsdt: \`0x\${string}\`;
  aavePool: \`0x\${string}\`;
};

export const addresses: Record<number, ContractAddresses> = {
  [HARDHAT_CHAIN_ID]: {
    factory: "${factoryAddr}",
    feeCollector: "${fcAddr}",
    registry: "${regAddr}",
    nft: "${nftAddr}",
    usdt: "${usdtAddr}",
    aUsdt: "${aTokenAddr}",
    aavePool: "${aavePoolAddr}",
  },
  [BSC_CHAIN_ID]: {
    factory: "0x0000000000000000000000000000000000000000",
    feeCollector: "0x0000000000000000000000000000000000000000",
    registry: "0x0000000000000000000000000000000000000000",
    nft: "0x0000000000000000000000000000000000000000",
    usdt: "0x55d398326f99059fF775485246999027b3197955",
    aUsdt: "0xf6C6361958652d87e07b46187513575975a6c016",
    aavePool: "0x6807dc960D6d17351D069670733D59634f9c169B",
  },
  [BSC_TESTNET_CHAIN_ID]: {
    factory: "0x0000000000000000000000000000000000000000",
    feeCollector: "0x0000000000000000000000000000000000000000",
    registry: "0x0000000000000000000000000000000000000000",
    nft: "0x0000000000000000000000000000000000000000",
    usdt: "0x0000000000000000000000000000000000000000",
    aUsdt: "0x0000000000000000000000000000000000000000",
    aavePool: "0x0000000000000000000000000000000000000000",
  },
};

export function getAddresses(chainId: number): ContractAddresses {
  const addrs = addresses[chainId];
  if (!addrs) {
    throw new Error(\`No contract addresses configured for chainId \${chainId}\`);
  }
  return addrs;
}
`;

  const outPath = path.resolve(__dirname, "../../lib/contracts/addresses.ts");
  fs.writeFileSync(outPath, addressesContent);
  console.log(`\nWrote addresses to ${outPath}`);

  console.log("\n╔══════════════════════════════════════════╗");
  console.log("║       LOCAL DEPLOYMENT COMPLETE          ║");
  console.log("╠══════════════════════════════════════════╣");
  console.log(`║  USDT (mock):    ${usdtAddr}  ║`);
  console.log(`║  Aave Pool:      ${aavePoolAddr}  ║`);
  console.log(`║  aToken:         ${aTokenAddr}  ║`);
  console.log(`║  FeeCollector:   ${fcAddr}  ║`);
  console.log(`║  Factory:        ${factoryAddr}  ║`);
  console.log(`║  Registry:       ${regAddr}  ║`);
  console.log(`║  NFT:            ${nftAddr}  ║`);
  console.log("╠══════════════════════════════════════════╣");
  console.log("║  Addresses auto-written to frontend.     ║");
  console.log("║  5 wallets funded with 100k USDT each.   ║");
  console.log("║                                          ║");
  console.log("║  Next: run `npm run dev` in root dir     ║");
  console.log("║  and connect MetaMask to localhost:8545   ║");
  console.log("╚══════════════════════════════════════════╝");

  console.log("\nTest accounts (import into MetaMask):");
  console.log("  Account #0:", deployer.address);
  console.log("    Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80");
  console.log("  Account #1:", alice.address);
  console.log("    Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d");
  console.log("  Account #2:", bob.address);
  console.log("    Key: 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
