// AUTO-GENERATED by deploy-local.ts — do not edit manually
export const BSC_CHAIN_ID = 56;
export const BSC_TESTNET_CHAIN_ID = 97;
export const HARDHAT_CHAIN_ID = 31337;

export type ContractAddresses = {
  factory: `0x${string}`;
  feeCollector: `0x${string}`;
  registry: `0x${string}`;
  nft: `0x${string}`;
  usdt: `0x${string}`;
  aUsdt: `0x${string}`;
  aavePool: `0x${string}`;
};

export const addresses: Record<number, ContractAddresses> = {
  [HARDHAT_CHAIN_ID]: {
    factory: "0x1138aD2d28c829bfB9780d4dbdb48cA52Be92e11",
    feeCollector: "0xc352C33435Cb76623a4D1E1944FE61ffbcaB4B08",
    registry: "0xdA1A82A0FEaDc237649BA33DB317499f8Fca3835",
    nft: "0x879AA6056BdEC81b325543763eF3C51Bf5dEFe05",
    usdt: "0xE82f2B0129206B65f7C214745a32de6E9B71C0F8",
    aUsdt: "0x569aF907f3152ff0189Bc9116d4B53dB94D51d96",
    aavePool: "0xC357B326Ff9d4930ad9b82E5f94f0bE49b73A4B6",
  },
  [BSC_CHAIN_ID]: {
    factory: "0x0000000000000000000000000000000000000000",
    feeCollector: "0x0000000000000000000000000000000000000000",
    registry: "0x0000000000000000000000000000000000000000",
    nft: "0x0000000000000000000000000000000000000000",
    usdt: "0x55d398326f99059fF775485246999027b3197955",
    aUsdt: "0xf6C6361958652d87e07b46187513575975a6c016",
    aavePool: "0x6807dc960D6d17351D069670733D59634f9c169B",
  },
  [BSC_TESTNET_CHAIN_ID]: {
    factory: "0x0000000000000000000000000000000000000000",
    feeCollector: "0x0000000000000000000000000000000000000000",
    registry: "0x0000000000000000000000000000000000000000",
    nft: "0x0000000000000000000000000000000000000000",
    usdt: "0x0000000000000000000000000000000000000000",
    aUsdt: "0x0000000000000000000000000000000000000000",
    aavePool: "0x0000000000000000000000000000000000000000",
  },
};

export function getAddresses(chainId: number): ContractAddresses {
  const addrs = addresses[chainId];
  if (!addrs) {
    throw new Error(`No contract addresses configured for chainId ${chainId}`);
  }
  return addrs;
}
