export const userData = {
  name: "Thabo Mokoena",
  address: "0x7a3b...9f4e",
  avatar: "TM",
  totalInvested: 3434.80,
  expectedTotalPot: 4218.55,
  earnedYield: 127.65,
  projectedYield: 783.75,
}

export const myCircles = [
  {
    id: "1",
    name: "Ubuntu Savers",
    type: "ROTATION" as const,
    members: 8,
    maxMembers: 10,
    contribution: 100,
    frequency: "Monthly",
    totalPot: 2400.00,
    accruedYield: 34.20,
    currentRound: 3,
    totalRounds: 10,
    status: "ACTIVE" as const,
    nextPayout: "Mar 1, 2026",
    nextRecipient: "Amara K.",
    isUserTurn: false,
    image: "",
  },
  {
    id: "2",
    name: "Kasi Builders Fund",
    type: "SAVINGS_SPLIT" as const,
    members: 5,
    maxMembers: 5,
    contribution: 250,
    frequency: "Monthly",
    totalPot: 6250.00,
    accruedYield: 89.40,
    currentRound: 5,
    totalRounds: 12,
    status: "ACTIVE" as const,
    maturityDate: "Dec 2026",
    nextPayout: "",
    nextRecipient: "",
    isUserTurn: false,
    image: "",
  },
  {
    id: "3",
    name: "Weekend Savers",
    type: "ROTATION" as const,
    members: 4,
    maxMembers: 6,
    contribution: 50,
    frequency: "Weekly",
    totalPot: 800.00,
    accruedYield: 5.12,
    currentRound: 2,
    totalRounds: 6,
    status: "OPEN" as const,
    nextPayout: "Feb 28, 2026",
    nextRecipient: "You",
    isUserTurn: true,
    image: "",
  },
]

export const publicCircles = [
  {
    id: "4",
    name: "Soweto Sisters",
    type: "ROTATION" as const,
    members: 7,
    maxMembers: 10,
    contribution: 200,
    frequency: "Monthly",
    totalPot: 4200.00,
    accruedYield: 58.30,
    verified: true,
  },
  {
    id: "5",
    name: "BSC Yield Collective",
    type: "SAVINGS_SPLIT" as const,
    members: 12,
    maxMembers: 20,
    contribution: 500,
    frequency: "Monthly",
    totalPot: 18000.00,
    accruedYield: 245.80,
    verified: true,
  },
  {
    id: "6",
    name: "Crypto Stokvel Alpha",
    type: "ROTATION" as const,
    members: 3,
    maxMembers: 8,
    contribution: 100,
    frequency: "Weekly",
    totalPot: 900.00,
    accruedYield: 12.60,
    verified: false,
  },
]

export const recentTransactions = [
  {
    id: "t1",
    type: "contribution" as const,
    circle: "Ubuntu Savers",
    amount: -100.00,
    date: "Feb 21, 2026",
    time: "04:36 PM",
    status: "Completed" as const,
    txId: "0x34422 87313",
  },
  {
    id: "t2",
    type: "payout" as const,
    circle: "Weekend Savers",
    amount: +196.00,
    date: "Feb 14, 2026",
    time: "11:20 AM",
    status: "Completed" as const,
    txId: "0x98f31 a2c04",
  },
  {
    id: "t3",
    type: "yield" as const,
    circle: "Kasi Builders Fund",
    amount: +12.40,
    date: "Feb 10, 2026",
    time: "08:00 AM",
    status: "Completed" as const,
    txId: "0x55d39 8326f",
  },
  {
    id: "t4",
    type: "contribution" as const,
    circle: "Kasi Builders Fund",
    amount: -250.00,
    date: "Feb 1, 2026",
    time: "09:15 AM",
    status: "Completed" as const,
    txId: "0xa7bc2 d4e19",
  },
]

export const circleDetailData = {
  id: "1",
  name: "Ubuntu Savers",
  description: "Monthly $100 rotation with friends and family. Building together, one round at a time.",
  type: "ROTATION" as const,
  status: "ACTIVE" as const,
  contribution: 100,
  frequency: "Monthly",
  members: [
    { name: "Thabo M.", address: "0x7a3b...9f4e", position: 1, hasReceived: true, contributed: 300, isActive: true, isUser: true },
    { name: "Amara K.", address: "0x1b2c...3d4e", position: 2, hasReceived: true, contributed: 300, isActive: true, isUser: false },
    { name: "Lerato S.", address: "0x5f6a...7b8c", position: 3, hasReceived: false, contributed: 300, isActive: true, isUser: false },
    { name: "Sipho N.", address: "0x9d0e...1f2a", position: 4, hasReceived: false, contributed: 300, isActive: true, isUser: false },
    { name: "Naledi D.", address: "0x3b4c...5d6e", position: 5, hasReceived: false, contributed: 200, isActive: true, isUser: false },
    { name: "Bongani M.", address: "0x7f8a...9b0c", position: 6, hasReceived: false, contributed: 300, isActive: true, isUser: false },
    { name: "Zanele P.", address: "0xd1e2...f3a4", position: 7, hasReceived: false, contributed: 300, isActive: true, isUser: false },
    { name: "Kgosi T.", address: "0x5b6c...7d8e", position: 8, hasReceived: false, contributed: 300, isActive: true, isUser: false },
  ],
  currentRound: 3,
  totalRounds: 8,
  totalPot: 2400.00,
  accruedYield: 34.20,
  userYieldShare: 13.68,
  protocolYieldShare: 20.52,
  withdrawalFee: 2,
  nextPayout: "Mar 1, 2026",
  currentRecipient: "Lerato S.",
  gracePeriod: "48h",
  missPolicy: "SKIP",
  payoutOrder: "FIXED",
  earlyExitAllowed: false,
  communityReserve: 0,
  joinVisibility: "INVITE_ONLY",
}

export const financeData = {
  totalExpenses: 2300.42,
  changePercent: 12,
  categories: [
    { name: "Contributions", amount: 1200, color: "var(--chart-1)", percent: 52 },
    { name: "Gas Fees", amount: 45.42, color: "var(--chart-2)", percent: 2 },
    { name: "Withdrawals", amount: 450, color: "var(--chart-3)", percent: 20 },
    { name: "Protocol Fees", amount: 105, color: "var(--chart-5)", percent: 5 },
    { name: "Others", amount: 500, color: "var(--muted-foreground)", percent: 21 },
  ],
  aiInsight: "Your savings circles generated 3.4% more yield this month compared to last. The Ubuntu Savers circle is performing best with consistent contributions from all members.",
}

export const referralNetwork = {
  user: {
    name: "Thabo Mokoena",
    address: "0x7a3b...9f4e",
    avatar: "TM",
    totalReferrals: 5,
    activeReferrals: 4,
    circlesFromReferrals: 3,
    referralCode: "THABO-M82K",
  },
  directInvites: [
    {
      id: "r1",
      name: "Amara Kofi",
      avatar: "AK",
      address: "0x1b2c...3d4e",
      joinedDate: "Jan 15, 2026",
      status: "active" as const,
      circlesCreated: [
        { name: "Soweto Sisters", members: 7, type: "ROTATION" as const },
      ],
      subInvites: [
        {
          id: "r1-1",
          name: "Zanele Pillay",
          avatar: "ZP",
          address: "0xd1e2...f3a4",
          joinedDate: "Feb 2, 2026",
          status: "active" as const,
          circlesCreated: [],
          subInvites: [],
        },
        {
          id: "r1-2",
          name: "Busi Ndaba",
          avatar: "BN",
          address: "0x22a1...c4b5",
          joinedDate: "Feb 10, 2026",
          status: "active" as const,
          circlesCreated: [
            { name: "Kasi Women Fund", members: 4, type: "SAVINGS_SPLIT" as const },
          ],
          subInvites: [],
        },
      ],
    },
    {
      id: "r2",
      name: "Sipho Nkosi",
      avatar: "SN",
      address: "0x9d0e...1f2a",
      joinedDate: "Jan 22, 2026",
      status: "active" as const,
      circlesCreated: [
        { name: "BSC Yield Collective", members: 12, type: "SAVINGS_SPLIT" as const },
      ],
      subInvites: [
        {
          id: "r2-1",
          name: "Kgosi Tau",
          avatar: "KT",
          address: "0x5b6c...7d8e",
          joinedDate: "Feb 18, 2026",
          status: "active" as const,
          circlesCreated: [],
          subInvites: [],
        },
      ],
    },
    {
      id: "r3",
      name: "Lerato Sello",
      avatar: "LS",
      address: "0x5f6a...7b8c",
      joinedDate: "Feb 5, 2026",
      status: "pending" as const,
      circlesCreated: [],
      subInvites: [],
    },
  ],
}
